spring.config.import=optional:file:./application-secret.properties
spring.application.name=imaji_coffee_be
server.port=${SERVER_PORT:8080}

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.root=${LOG_LEVEL:INFO}
logging.pattern.file={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}

spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:imajicoffee}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=5m

management.endpoint.health.show-details=never
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.configprops.show-values=never
management.endpoint.env.show-values=never

stripe.secretKey=${STRIPE_SECRET_KEY:dummy}
stripe.webhook.secretKey=${STRIPE_WEBHOOK_SECRET:dummy}

imajicoffee.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
jwt.secret=${JWT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:dummy@example.com}
spring.mail.password=${MAIL_PASSWORD:dummy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dummy}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy}
spring.security.oauth2.client.registration.google.scope=email,profile

app.frontend.redirect-url=${FRONT_END_CALL_BACK_URL:http://localhost:5173/auth/callback}
server.forward-headers-strategy=framework


# Local Docker example -> want to create docker image on your own -> try this
# sudo docker run -p 3306:3306 \
#   --name imajicoffeedb \
#   -e MYSQL_ROOT_PASSWORD=your_password \
#   -e MYSQL_DATABASE=imajicoffee \
#   -v /Users/yourname/imaji_coffee/db:/var/lib/mysql \
#   -d mysql
